(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Title: Information *)
(* :Context: SciDraw` *)
(* :Summary: Package version information and history comments *)
(* :Author: Mark A. Caprio, Department of Physics, University of Notre Dame *)
(* :Copyright: Copyright 2015, Mark A. Caprio *)
(* :Package Version: See $FigVersionString below. *)
(* :Mathematica Version: 10.0 *)
(* :Discussion:  

Use of the software is subject to the CPCPL Non\[Dash]Profit Use Licence Agreement (http://cpc.cs.qub.ac.uk/licence/licence.html).

Updates and further information may be obtained through the SciDraw home page at scidraw.nd.edu.  

If you modify the software, please change $FigVersionString below, and thus the message displayed when the package is loaded, to clearly indicate that the package is a modified version. 

*)
(* :History:  Successor to LevelScheme package, for which early ancestor code was begun July 1999.  Development of SciDraw begun May 2011.
*)


BeginPackage["SciDraw`"];


Unprotect[Evaluate[$Context<>"*"]];


Begin["`Private`"];





$ExternalContexts={"Units`","MathObject`","MathObject`Methods`","MathObject`InstanceData`","InheritOptions`","NamedColors`","CustomTicks`","BlockOptions`","Profile`","StyleOptions`"};


$FigVersionNumber=0.0;
$FigReleaseNumber=6;
$FigVersionString="0.0.7 (March 28, 2015)";
$FigVersionURL="http://scidraw.nd.edu/landing/scidraw-0.0.7.html";


End[];


Protect[Evaluate[$Context<>"*"]];
Unprotect[Evaluate[$Context<>"$*"]];
EndPackage[];
