(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* :Title: Common *)
(* :Context: SciDraw` *)
(* :Summary: Common global constants and flag variables *)
(* :Author: Mark A. Caprio, Department of Physics, University of Notre Dame *)
(* :Copyright: Copyright FIGYEAR, Mark A. Caprio *)
(* :Package Version: FIGVERSION *)
(* :Mathematica Version: MATHVERSION *)
(* :Discussion: FIGDISCUSSION *)
(* :History: See package information file. *)


BeginPackage["SciDraw`",SciDraw`Private`$ExternalContexts];


Unprotect[Evaluate[$Context<>"*"]];


Begin["`Private`"];





$FigBackgroundLayer=0;
$FigDrawingLayer=1;
$FigBlankingLayer=2;
$FigTextLayer=3;


$FigTextBaseBuffer=1;


$FigOptionRules={};


$InFigure=False;


$FigBaseStyle;


$GraphicalElementList;


$CanvasBaseRange;
$CanvasFullRange;
$CanvasDimensions;
$TickScaleFactor;


$CanvasWindow;
$CurrentWindow;


$Multipanel=None;


$CanvasBackground;
$CurrentBackground;


$PrintTiming=False;
$DebugOptionOverrides=False;


End[];


Protect[Evaluate[$Context<>"*"]];
Unprotect[Evaluate[$Context<>"$*"]];
EndPackage[];
